[functions]
  directory = "functions"   # ← Netlify picks up chat.js here

# Redirect every /api/* path to the matching function
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

  